version: '3.8'

services:
  neo4j:
    image: neo4j:5.13
    container_name: neo4j_badevel
    restart: always
    environment:
      - NEO4J_AUTH=neo4j/Password123
      - NEO4JLABS_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    networks:
      - badevel_network

  backend:
    build: ./backend
    container_name: backend_badevel
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - neo4j
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=Password123
    networks:
      - badevel_network

  frontend:
    build: ./frontend
    container_name: frontend_badevel
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - badevel_network

networks:
  badevel_network:
    name: badevel_network

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:
